### ISSUE TITLE
Enhancement: Mirror existing theme with no background for transparent terminals

### ISSUE THREAD

**Issue by poetaman** [shuber2/mutt-gruvbox#2]
There is a rising trend of among developers to use semi-transparent backgrounds for terminals. To support such a cause, an enhancement can be to have no background specified by mutt & user gets to set their terminal's semi-transparent background. Am new to mutt, so don't know if it can be a conditional/variable.

**Comment by shuber2** [comment]
I guess it depends on the terminal. In konsole the transparency setting also works for the current colorscheme. Maybe other terminals need "default" as background color. But then for all other users the background becomes black, making the colorscheme much harder.

I am closing this issue because I do not see right now how to proceed. However, I am happy to merge a pull request that improves the experience for transparent backgrounds and maintains the experience for non-transparent backgrounds.
